const data = [
    {
      "date": "2024-12-10T21:30:00",
      "disaster_type": "Bus Accident",
      "likes": null,
      "location": "Kurla, Mumbai",
      "post_body": "A tragic bus accident in Kurla, Mumbai, last night killed seven and injured 42. A BEST electric bus lost control and collided with pedestrians and vehicles. The driver has been arrested. Investigations are ongoing.",
      "post_body_full": "Last night, a deadly bus accident occurred in Kurla, Mumbai, involving a BEST electric bus that collided with pedestrians and vehicles, causing seven fatalities and 42 injuries. The driver has been arrested. Investigations are ongoing.",
      "post_id": "1a2b3c4d5e",
      "post_image_b64": null,
      "post_image_url": "https://img.etimg.com/thumb/msid-116205994,width-300,height-225,imgsize-77084,resizemode-75/mumbai-best-bus-accident.jpg",
      "post_title": "Deadly Bus Accident in Kurla: 7 Dead, 42 Injured",
      "priority": "high",
      "retweets": null,
      "source": "MumbaiNews24",
      "url": "https://economictimes.indiatimes.com/news/mumbai-news/mumbai-kurla-bus-accident-brake-failure-lack-of-training-or-intentional-what-caused-the-deadly-accident-claiming-7-lives/articleshow/116204819.cms?from=mdr",
      "username": null
    },
{
      "date": "2024-12-10T21:45:00",
      "disaster_type": "Bus Accident",
      "likes": null,
      "location": "Kurla, Mumbai",
      "post_body": "A devastating accident in Kurla involving a BEST electric bus claimed seven lives. Reports suggest driver panic after an initial crash. 42 others injured. Investigations are ongoing.",
      "post_body_full": "In the late hours of Monday, a BEST electric bus lost control and crashed into pedestrians and vehicles in Kurla, Mumbai, killing seven and injuring 42. The driver was arrested, and investigations are ongoing.",
      "post_id": "2f3g4h5i6j",
      "post_image_b64": null,
      "post_image_url": "https://img.etimg.com/thumb/msid-116205994,width-300,height-225,imgsize-77084,resizemode-75/mumbai-best-bus-accident.jpg",
      "post_title": "7 Killed, 42 Injured in Mumbai BEST Bus Crash",
      "priority": "high",
      "retweets": null,
      "source": "MumbaiTimes",
      "url": "https://economictimes.indiatimes.com/news/mumbai-news/mumbai-kurla-bus-accident-brake-failure-lack-of-training-or-intentional-what-caused-the-deadly-accident-claiming-7-lives/articleshow/116204819.cms?from=mdr",
      "username": null
},
{
      "date": "2024-12-10T22:00:00",
      "disaster_type": "Bus Accident",
      "likes": null,
      "location": "Kurla, Mumbai",
      "post_body": "Seven lives lost and 42 others injured in a Kurla bus accident. Cause under investigation. The driver has been arrested. Investigations are ongoing.",
      "post_body_full": "At 9:30 PM, a BEST electric bus collided with pedestrians and vehicles in Kurla, Mumbai, resulting in seven deaths and 42 injuries. Investigations are ongoing, and the driver has been arrested.",
      "post_id": "3k4l5m6n7o",
      "post_image_b64": null,
      "post_image_url": "https://img.etimg.com/thumb/msid-116205994,width-300,height-225,imgsize-77084,resizemode-75/mumbai-best-bus-accident.jpg",
      "post_title": "Tragic Bus Accident in Kurla: 7 Dead, 42 Hurt",
      "priority": "high",
      "retweets": null,
      "source": "Economic Times",
      "url": "https://economictimes.indiatimes.com/news/mumbai-news/mumbai-kurla-bus-accident-brake-failure-lack-of-training-or-intentional-what-caused-the-deadly-accident-claiming-7-lives/articleshow/116204819.cms?from=mdr",
      "username": null
},
{
  
      "date": "2024-12-0820:00:00",
      "disaster_type": "Flood",
      "hastags": ["#CycloneFengal", "#Buffaloes", "#Floods"],
      "likes": null,
      "location": "India",
      "post_body": "Nearly 32 buffaloes were swept away during the devastating floods caused by Cyclone Fengal. One buffalo, captured in a viral video, is seen struggling to survive even after six days. Watch the full video here. #CycloneFengal #Buffaloes #Floods",
      "post_body_full": "Cyclone Fengal wreaked havoc on India, with nearly 32 buffaloes swept away in the devastating floods. A heartbreaking video shows one buffalo clinging to life even after six days. Captured by a fisherman on Sunday, the visuals of the cattle drifting helplessly in the open waters have gone viral. Watch the full video: [Cyclone Fengal: Buffalo swept away clings to life even after six days](https://www.indiatoday.in/india/video/cyclone-fengal-buffalo-swept-away-clings-life-even-after-six-days-2646797-2024-12-08). #CycloneFengal #Buffaloes #Floods",
      "post_id": "4a5b6c7d8e",
      "post_image_b64": null,
      "post_image_url": "https://www.indiatoday.in/india/video/cyclone-fengal-buffalo-swept-away-clings-life-even-after-six-days-2646797-2024-12-08",
      "post_title": "Buffalo Clings to Life Six Days After Being Swept Away by Cyclone Fengal",
      "priority": "high",
      "retweets": null,
      "source": "IndiaToday",
      "url": "https://www.indiatoday.in/india/video/cyclone-fengal-buffalo-swept-away-clings-life-even-after-six-days-2646797-2024-12-08",
      "username": null

},
{
  
      "date": "2024-12-07T03:00:00",
      "disaster_type": "Cyclone",
      "hastags": ["#CycloneFengal", "#TamilNadu", "#Puducherry"],
      "likes": 700,
      "location": "Tiruvannamalai, Tamil Nadu",
      "post_body": "Cyclone Fengal has caused widespread devastation in Tamil Nadu & Puducherry, claiming 12 lives and affecting 14 districts. A landslide in VOC Nagar killed 7 people. Rescue ops continue. #CycloneFengal #TamilNadu #Puducherry",
      "post_body_full": "Cyclone Fengal hit Tamil Nadu and Puducherry with full force, causing massive destruction. In VOC Nagar, Tiruvannamalai, a landslide took 7 lives, and overall, 12 people have died. The cyclone’s unpredictable course left authorities scrambling. #CycloneFengal #TamilNadu #Puducherry",
      "post_id": "1z2a3b4c5d",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/eu12dx/article68956172.ece/alternates/LANDSCAPE_1200/9712_2_12_2024_15_45_21_2__DSC4458.JPG",
      "post_title": "Cyclone Fengal Wreaks Havoc in Tamil Nadu & Puducherry",
      "priority": "high",
      "retweets": 250,
      "source": "Twitter",
      "url": "https://www.thehindu.com/news/national/tamil-nadu/cyclone-fengal-leaves-12-dead/article68956172.ece",
      "username": "siddhiawari"

},
{

      "date": "2024-12-07T03:00:00",
      "disaster_type": "Cyclone",
      "hastags": null,
      "likes": null,
      "location": "Tiruvannamalai, Tamil Nadu",
      "post_body": "Cyclone Fengal, which struck Tamil Nadu and Puducherry, has claimed 12 lives and left extensive damage. In VOC Nagar, a landslide tragically killed 7 people. The rescue operation is ongoing. More details to follow.",
      "post_body_full": "Cyclone Fengal, which impacted Tamil Nadu and Puducherry, caused the death of 12 people and severe damage across 14 districts. In VOC Nagar, Tiruvannamalai, seven people were killed by a landslide. Rescue operations are in full swing, with 170 personnel involved. The cyclone's erratic path presented challenges to authorities, despite preparedness. The situation remains critical, and further updates will follow.",
      "post_id": "5e6f7g8h9i",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/eu12dx/article68956172.ece/alternates/LANDSCAPE_1200/9712_2_12_2024_15_45_21_2__DSC4458.JPG",
      "post_title": "Cyclone Fengal Leaves 12 Dead, 7 Killed in Landslide in Tamil Nadu",
      "priority": "high",
      "retweets": null,
      "source": "The Hindu",
      "url": "https://www.thehindu.com/news/national/tamil-nadu/cyclone-fengal-leaves-12-dead/article68956172.ece",
      "username": "TheHindu"
},
{
      "date": "2024-12-16T01:30:00",
      "disaster_type": "Landslide",
      "hastags": ["#Wayanad", "#Kerala", "#Landslide"],
      "likes": 500,
      "location": "Wayanad, Kerala",
      "post_body": "A devastating landslide hit Chooralmala and Mundakkai villages in Wayanad, Kerala, claiming over 230 lives and leaving more than 130 people missing. The disaster is one of Kerala's worst since the 2018 floods. #Wayanad #Kerala #Landslide",
      "post_body_full": "On July 30, 2024, Chooralmala and Mundakkai villages in Wayanad, Kerala, were struck by massive landslides triggered by heavy rainfall. Over 230 lives have been lost, with more than 130 people still missing. These villages, known for their scenic beauty, are now the site of a major natural disaster. #Wayanad #Kerala #Landslide",
      "post_id": "1d2e3f4g5h",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/jtgue3/article68502865.ece/alternates/LANDSCAPE_1200/PTI08_01_2024_000579B.jpg",
      "post_title": "Wayanad Landslide: Over 230 Dead, 130 Missing",
      "priority": "high",
      "retweets": 180,
      "source": "Twitter",
      "url": "https://www.thehindu.com/news/national/south/kerala-wayanad-landslide/article68502865.ece",
      "username": "siddhiawari"
},
{
      "date": "2024-12-16T11:34:00",
      "disaster_type": "Landslide",
      "Hastags": null,
      "likes": null,
      "location": "Wayanad, Kerala",
      "post_body": "A deadly landslide in Wayanad, Kerala, has claimed more than 230 lives, with over 130 people still missing. The landslides in Chooralmala and Mundakkai villages have been one of the worst natural disasters in Kerala since the 2018 floods.",
      "post_body_full": "In the early hours of July 30, 2024, landslides struck the scenic villages of Chooralmala and Mundakkai in Wayanad, Kerala, killing over 230 people. As of August 13, more than 130 individuals are still missing. The disaster, triggered by heavy rainfall, has caused immense devastation in these villages, known for their waterfalls and landscapes. Rescue operations are ongoing, and the full extent of the damage is still unknown.",
      "post_id": "2m3n4o5p6q",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/jtgue3/article68502865.ece/alternates/LANDSCAPE_1200/PTI08_01_2024_000579B.jpg",
      "post_title": "Landslides in Wayanad, Kerala: Over 230 Dead, 130 Missing",
      "priority": "high",
      "retweets": null,
      "source": "The Hindu",
      "url": "https://www.thehindu.com/news/national/south/kerala-wayanad-landslide/article68502865.ece",
      "username": "TheHindu"
},
{
      "date": "2024-12-11T06:22:00",
      "disaster_type": "Explosion",
      "likes": null,
      "location": "Anakapalli, Andhra Pradesh",
      "post_body": "At least 14 workers were killed and several others injured in a massive explosion at the Escientia pharmaceutical unit in Andhra Pradesh's Atchutapuram SEZ. A highly inflammable solvent leak was the cause of the blast. Rescue operations are still underway.",
      "post_body_full": "On December 8, 2024, a powerful explosion rocked the Escientia pharmaceutical plant in Andhra Pradesh's Atchutapuram SEZ. The explosion claimed the lives of 14 workers, with many others injured. Authorities revealed that the blast was triggered by a leak of a highly inflammable solvent used in the unit’s processes. Rescue operations are still ongoing, and investigations are in progress.",
      "post_id": "3p4q5r6s7t",
      "post_image_b64": null,
      "post_image_url": "https://www.indiatoday.in/india/video/explosion-pharmaceutical-plant-14-killed-andhra-pradesh-2646797-2024-12-11",
      "post_title": "Explosion at Escientia Pharma Unit in Andhra: 14 Dead, Several Injured",
      "priority": "high",
      "retweets": null,
      "source": "IndiaToday",
      "url": "https://www.indiatoday.in/india/video/explosion-pharmaceutical-plant-14-killed-andhra-pradesh-2646797-2024-12-11",
      "username": null
},
{
      "date": "2024-12-11T06:22:00",
      "disaster_type": "Explosion",
      "likes": null,
      "location": "Anakapalli, Andhra Pradesh",
      "post_body": "At least 14 workers were killed and several others injured in a massive explosion at the Escientia pharmaceutical unit in Andhra Pradesh's Atchutapuram SEZ. A highly inflammable solvent leak was the cause of the blast. Rescue operations are still underway.",
      "post_body_full": "On December 8, 2024, a powerful explosion rocked the Escientia pharmaceutical plant in Andhra Pradesh's Atchutapuram SEZ. The explosion claimed the lives of 14 workers, with many others injured. Authorities revealed that the blast was triggered by a leak of a highly inflammable solvent used in the unit’s processes. Rescue operations are still ongoing, and investigations are in progress.",
      "post_id": "3p4q5r6s7t",
      "post_image_b64": null,
      "post_image_url": "https://www.indiatoday.in/india/video/explosion-pharmaceutical-plant-14-killed-andhra-pradesh-2646797-2024-12-11",
      "post_title": "Explosion at Escientia Pharma Unit in Andhra: 14 Dead, Several Injured",
      "priority": "high",
      "retweets": null,
      "source": "IndiaToday",
      "url": "https://www.indiatoday.in/india/video/explosion-pharmaceutical-plant-14-killed-andhra-pradesh-2646797-2024-12-11",
      "username": null
},
{
      "date": "2024-12-11T09:30:00",
      "disaster_type": "Explosion",
      "Hastags": null,
      "likes": null,
      "location": "Anakapalli, Andhra Pradesh",
      "post_body": "A tragic explosion at the Escientia pharmaceutical plant in Andhra Pradesh’s Atchutapuram SEZ has resulted in 17 deaths. Preliminary investigations indicate a leak of an inflammable solvent triggered the blast.",
      "post_body_full": "The Escientia pharmaceutical plant in Atchutapuram SEZ, Andhra Pradesh, was the site of a devastating explosion on December 11, 2024. The explosion claimed the lives of 17 workers and caused significant damage. Investigators have confirmed that the explosion was caused by a leak of Methyl Tert-Butyl Ether (MTBE), a highly flammable solvent used in the pharmaceutical industry. The incident occurred during a shift change when several workers were on site. The situation is still under investigation.",
      "post_id": "2a3b4c5d6e",
      "post_image_b64": null,
      "post_image_url": "https://images.indianexpress.com/2024/12/andhra.jpg?w=640",
      "post_title": "Escientia Pharma Plant Explosion: 17 Dead, Many Injured",
      "priority": "high",
      "retweets": null,
      "source": "Times of India",
      "url": "https://timesofindia.indiatimes.com/articleshow/116204719.cms",
      "username": null
},
{
      "date": "2024-12-11T12:00:00",
      "disaster_type": "Explosion",
      "Hastags": null,
      "likes": null,
      "location": "Anakapalli, Andhra Pradesh",
      "post_body": "A catastrophic explosion at a pharmaceutical factory in Andhra’s Atchutapuram SEZ has killed at least 14 people and left many injured. Emergency teams are still working to rescue those trapped.",
      "post_body_full": "A catastrophic explosion took place at the Escientia pharmaceutical plant located in Atchutapuram SEZ, Anakapalli, Andhra Pradesh, on December 11, 2024. The blast, caused by the leakage of Methyl Tert-Butyl Ether (MTBE), killed at least 14 workers and left several others with severe injuries. Rescue operations are ongoing, as many workers are feared trapped under debris. Authorities have initiated an investigation to determine the exact cause of the explosion.",
      "post_id": "3f4g5h6i7j",
      "post_image_b64": null,
      "post_image_url": "https://images.indianexpress.com/2024/12/andhra.jpg?w=640",
      "post_title": "Explosion at Andhra Pharma Factory Kills 14, Injures Several Others",
      "priority": "high",
      "retweets": null,
      "source": "NDTV",
      "url": "https://ndtv.com/andhra-pradesh/andhra-pharma-explosion-kills-14-articleshow/6509852/",
      "username": null
},
{
      "date": "2024-12-11T00:00:00",
      "disaster_type": "Cyclone",
      "Hastags": null,
      "likes": null,
      "location": "India, Bangladesh",
      "post_body": "Cyclone Remal has left over 54 dead across India and Bangladesh, with 3.75 million people affected. Thousands of houses have been destroyed, and large-scale evacuations continue.",
      "post_body_full": "Cyclone Remal struck northeastern India and Bangladesh from December 6-8, 2024, resulting in significant casualties and destruction. In India, 39 fatalities were reported, with the highest number in Mizoram, and 15 others across other states. Bangladesh reported 16 fatalities and extensive damage to homes and infrastructure. Over 800,000 people were evacuated across both nations, and large areas of agricultural land were inundated. The humanitarian crisis is intensifying as rescue and relief efforts continue.",
      "post_id": "1a2b3c4d5e",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/jtgue3/article68502865.ece/alternates/LANDSCAPE_1200/PTI08_01_2024_000579B.jpg",
      "post_title": "Cyclone Remal Devastates India and Bangladesh: Over 54 Dead, Millions Affected",
      "priority": "high",
      "retweets": null,
      "source": "ECHO",
      "url": "https://echo.unhcr.org/cyclone-remal",
      "username": null
},
{
      "date": "2024-12-11T00:00:00",
      "disaster_type": "Cyclone",
      "Hastags": null,
      "likes": null,
      "location": "India, Bangladesh",
      "post_body": "Cyclone Remal leaves extensive damage in India and Bangladesh. Over 800,000 people evacuated in Bangladesh. Millions remain displaced.",
      "post_body_full": "Cyclone Remal, which made landfall near the Bangladesh-India border on December 6, 2024, has caused widespread damage across both nations. In Bangladesh, 807,000 people were evacuated across 9,424 shelters. The cyclone's aftermath has left over 173,000 homes damaged, with thousands displaced. India has reported over 37 fatalities, and many more are still missing. Relief efforts are underway, but challenges remain as flooding and landslides continue.",
      "post_id": "2b3c4d5e6f",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/jtgue3/article68502865.ece/alternates/LANDSCAPE_1200/PTI08_01_2024_000579B.jpg",
      "post_title": "Cyclone Remal Evacuations, Casualties, and Destruction in India and Bangladesh",
      "priority": "high",
      "retweets": null,
      "source": "IFRC",
      "url": "https://ifrc.org/cyclone-remal-impact",
      "username": null
},
{
      "date": "2024-12-11T00:00:00",
      "disaster_type": "Cyclone",
      "Hastags": null,
      "likes": null,
      "location": "Bangladesh",
      "post_body": "Cyclone Remal's devastation continues in Bangladesh, with over 4.6 million affected. The cyclone caused severe flooding, displacement, and crop damage.",
      "post_body_full": "Cyclone Remal struck Bangladesh in December 2024, affecting over 4.6 million people in 19 districts. Approximately 173,000 houses were damaged, and thousands of acres of agricultural land were inundated. Over 80,000 hectares of farmland were flooded, causing significant damage to crops and livelihoods. The government has been working to provide relief, but the ongoing rains and unrest in the country complicate efforts to deliver aid.",
      "post_id": "3d4e5f6g7h",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/jtgue3/article68502865.ece/alternates/LANDSCAPE_1200/PTI08_01_2024_000579B.jpg",
      "post_title": "Cyclone Remal: Bangladesh Faces Widespread Damage, Over 4.6 Million Affected",
      "priority": "high",
      "retweets": null,
      "source": "UNICEF",
      "url": "https://unicef.org/cyclone-remal-bangladesh",
      "username": null
},
{
      "date": "2024-12-11T00:00:00",
      "disaster_type": "Cyclone",
      "Hastags": null,
      "likes": null,
      "location": "Bangladesh",
      "post_body": "Cyclone Remal leaves Bangladesh in ruins. Hundreds of thousands of people have been evacuated as the cyclone continues to affect coastal areas.",
      "post_body_full": "The ongoing impacts of Cyclone Remal in Bangladesh, particularly in coastal districts, have led to large-scale evacuations, with over 800,000 people moved to shelters. Significant flooding and damage to critical infrastructure have made relief efforts challenging. The cyclone has devastated large agricultural regions, with crops destroyed and many lives lost. The situation remains dire as the cyclone’s effects linger on.",
      "post_id": "4a5b6c7d8e",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/jtgue3/article68502865.ece/alternates/LANDSCAPE_1200/PTI08_01_2024_000579B.jpg",
      "post_title": "Cyclone Remal Devastates Bangladesh, Thousands Evacuated",
      "priority": "high",
      "retweets": null,
      "source": "Reuters",
      "url": "https://reuters.com/cyclone-remal-bangladesh-evacuations",
      "username": null
},
{
      "date": "2024-05-12T13:26:00",
      "disaster_type": "Flood",
      "Hastags": null,
      "likes": null,
      "location": "Sikkim, India",
      "post_body": "The October 2023 glacial lake outburst flood in Sikkim led to the collapse of the Teesta III hydroelectric dam and claimed more than 100 lives. Thousands were affected by the devastating floods.",
      "post_body_full": "A glacial lake outburst flood (GLOF) in October 2023 in Sikkim caused widespread destruction, leading to the collapse of the Teesta III hydroelectric dam and claiming more than 100 lives. Thousands of people were affected, and the disaster was one of the worst climate-related events in Asia in 2023, according to the World Meteorological Organization’s 'State of the Climate Asia 2023' report.",
      "post_id": "a1b2c3d4e5",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/v1eu39/article68152221.ece/alternates/LANDSCAPE_1200/2150_13_10_2023_9_15_40_1_SIKKIM_11102023_18.JPG",
      "post_title": "Sikkim Flood: One of Asia’s Worst Climate Disasters in 2023",
      "priority": "high",
      "retweets": null,
      "source": "The Hindu",
      "url": "https://www.thehindu.com/sci-tech/energy-and-environment/sikkim-2023-glacial-lake-outburst-flood-climate-change-analysis/article68152208.ece",
      "username": null
},
{
      "date": "2024-05-12T14:30:00",
      "disaster_type": "Flood",
      "Hastags": null,
      "likes": null,
      "location": "Sikkim, India",
      "post_body": "A sudden outburst of a glacial lake in Sikkim in 2023 led to catastrophic flooding, damaging homes and infrastructure, leaving thousands stranded.",
      "post_body_full": "The glacial lake outburst flood in Sikkim in October 2023 caught many residents off-guard, leading to the collapse of essential infrastructure and the destruction of homes. With over 100 lives lost and hundreds more displaced, the flood is considered one of the most devastating climate-induced disasters in the region. Experts have pointed out the link between rising temperatures and increased frequency of such events in the Himalayas.",
      "post_id": "f6g7h8i9j0",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/v1eu39/article68152221.ece/alternates/LANDSCAPE_1200/2150_13_10_2023_9_15_40_1_SIKKIM_11102023_18.JPG",
      "post_title": "Sikkim’s Glacial Lake Outburst Flood: A Climate Crisis",
      "priority": "high",
      "retweets": null,
      "source": "Environmental News Today",
      "url": "https://www.environmentnews.com/sikkim-flood-2023",
      "username": null
},
{
      "date": "2024-05-12T15:45:00",
      "disaster_type": "Flood",
      "Hastags": null,
      "likes": null,
      "location": "Sikkim, India",
      "post_body": "The 2023 glacial lake outburst flood in Sikkim has been identified as one of the most severe climate events in Asia, leaving over 100 dead and thousands homeless.",
      "post_body_full": "The 2023 glacial lake outburst flood in Sikkim was a significant climate disaster that led to the collapse of the Teesta III hydroelectric dam and caused widespread destruction. More than 100 people lost their lives, and thousands of families were displaced. This event has raised alarms about the vulnerability of the region’s infrastructure and ecosystems to climate change. The flood was ranked as one of Asia’s worst climate disasters of 2023.",
      "post_id": "k1l2m3n4o5",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/v1eu39/article68152221.ece/alternates/LANDSCAPE_1200/2150_13_10_2023_9_15_40_1_SIKKIM_11102023_18.JPG",
      "post_title": "2023 Sikkim Flood: A Devastating Climate Disaster",
      "priority": "high",
      "retweets": null,
      "source": "Global Disaster Watch",
      "url": "https://www.globaldisasterwatch.org/sikkim-flood-2023",
      "username": null
},
{
      "date": "2024-05-12T16:00:00",
      "disaster_type": "Flood",
      "Hastags": null,
      "likes": null,
      "location": "Sikkim, India",
      "post_body": "Sikkim’s October 2023 glacial lake outburst flood has caused massive destruction, with over 100 lives lost and widespread damage to infrastructure.",
      "post_body_full": "The October 2023 glacial lake outburst flood in Sikkim led to the collapse of the Teesta III hydroelectric dam and caused massive destruction across the region. Over 100 people were killed, and thousands were displaced. Experts warn this could be a sign of increasing climate risks in the region.",
      "post_id": "t1u2v3w4x5",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/v1eu39/article68152221.ece/alternates/LANDSCAPE_1200/2150_13_10_2023_9_15_40_1_SIKKIM_11102023_18.JPG",
      "post_title": "Sikkim Flood 2023: A Wake-up Call for Climate Action",
      "priority": "high",
      "retweets": null,
      "source": "Climate Change Watch",
      "url": "https://www.climatechange.org/sikkim-glacial-flood-2023",
      "username": null
},
{
      "date": "2024-05-12T16:30:00",
      "disaster_type": "Flood",
      "Hastags": null,
      "likes": null,
      "location": "Sikkim, India",
      "post_body": "The glacial lake outburst flood in Sikkim in 2023 has been recognized as one of Asia’s worst climate-related disasters, with severe impacts on the population.",
      "post_body_full": "In October 2023, a glacial lake outburst flood in Sikkim caused one of the worst climate-related disasters in Asia. The flood led to the collapse of a hydroelectric dam, and over 100 people lost their lives. Thousands of others were left stranded as infrastructure was destroyed.",
      "post_id": "z1y2x3w4v5",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/v1eu39/article68152221.ece/alternates/LANDSCAPE_1200/2150_13_10_2023_9_15_40_1_SIKKIM_11102023_18.JPG",
      "post_title": "Sikkim 2023: A Climate Disaster of Epic Proportions",
      "priority": "high",
      "retweets": null,
      "source": "Environmental News Today",
      "url": "https://www.environmentnews.com/sikkim-flood-2023",
      "username": null
},
{
      "date": "2024-05-12T17:00:00",
      "disaster_type": "Flood",
      "Hastags": null,
      "likes": null,
      "location": "Sikkim, India",
      "post_body": "The Sikkim flood of 2023, caused by a glacial lake outburst, led to catastrophic damage. Over 100 people were killed and thousands affected.",
      "post_body_full": "The October 2023 glacial lake outburst flood in Sikkim caused massive damage, leading to the collapse of infrastructure and the loss of over 100 lives. Thousands were displaced. This climate disaster underscores the growing risks in mountainous regions due to global warming.",
      "post_id": "p1q2r3s4t5",
      "post_image_b64": null,
      "post_image_url": "https://th-i.thgim.com/public/incoming/v1eu39/article68152221.ece/alternates/LANDSCAPE_1200/2150_13_10_2023_9_15_40_1_SIKKIM_11102023_18.JPG",
      "post_title": "2023 Sikkim Flood: A Major Climate Crisis",
      "priority": "high",
      "retweets": null,
      "source": "Global Disaster Watch",
      "url": "https://www.globaldisasterwatch.org/sikkim-flood-2023",
      "username": null
},
{
      "date": "2024-12-10T10:00:00",
      "disaster_type": "Landslide",
      "Hastags": null,
      "likes": null,
      "location": "Himachal Pradesh, India",
      "post_body": "Himachal Pradesh faced severe landslides in July 2023 due to heavy rainfall, leading to significant destruction and loss of life.",
      "post_body_full": "Intense rainfall in Himachal Pradesh from 7 to 14 July 2023 triggered over 5,400 landslides and flash floods, causing widespread devastation. The event resulted in 223 lives lost, 70,000 tourists stranded, and over 1,300 road closures. A detailed study published in the journal Landslides highlights the unprecedented nature of this disaster, driven by monsoonal troughs and active disturbances.",
      "post_id": "l1a2n3d4s5",
      "post_image_b64": null,
      "post_image_url": "https://i0.wp.com/eos.org/wp-content/uploads/2024/01/24_01-India-1.jpg?w=581&ssl=1",
      "post_title": "Severe Landslides in Himachal Pradesh: July 2023 Disaster Report",
      "priority": "high",
      "retweets": null,
      "source": "Himalayan Times",
      "url": "https://eos.org/thelandslideblog/himachal-pradesh-1",
      "username": null
},
{
      "date": "2024-12-10T12:30:00",
      "disaster_type": "Landslide",
      "Hastags": null,
      "likes": null,
      "location": "Himachal Pradesh, India",
      "post_body": "Over 5,400 landslides were reported in Himachal Pradesh during intense monsoon rains in July 2023, stranding thousands of tourists.",
      "post_body_full": "During July 2023, heavy monsoonal rains led to catastrophic landslides across Himachal Pradesh, with over 5,400 reported between 9 and 11 July. The disaster caused severe disruptions, including 1,300 road closures and flash floods, resulting in the loss of 223 lives. The state's infrastructure faced massive damage, stranding 70,000 tourists and affecting thousands of locals.",
      "post_id": "l2m3n4d5s6",
      "post_image_b64": null,
      "post_image_url": "https://i0.wp.com/eos.org/wp-content/uploads/2024/01/24_01-India-1.jpg?w=581&ssl=1",
      "post_title": "Himachal Pradesh Landslides: Monsoon Fury in July 2023",
      "priority": "high",
      "retweets": null,
      "source": "Mountain Safety Journal",
      "url": "https://eos.org/thelandslideblog/himachal-pradesh-1",
      "username": null
},
{
      "date": "2024-12-10T15:00:00",
      "disaster_type": "Landslide",
      "Hastags": null,
      "likes": null,
      "location": "Himachal Pradesh, India",
      "post_body": "Himachal Pradesh experienced catastrophic landslides in July 2023, with flash floods and heavy rainfall leaving thousands stranded.",
      "post_body_full": "A new study sheds light on the devastation caused by landslides in Himachal Pradesh from 7 to 14 July 2023. Over 5,400 landslides were triggered by intense rainfall, along with 29 flash floods. The event resulted in the tragic loss of 223 lives and disrupted transportation with 1,300 road closures. This disaster highlighted the vulnerability of mountainous regions to extreme weather.",
      "post_id": "l3p4q5r6s7",
      "post_image_b64": null,
      "post_image_url": "https://i0.wp.com/eos.org/wp-content/uploads/2024/01/24_01-India-1.jpg?w=581&ssl=1",
      "post_title": "Landslide Disaster in Himachal Pradesh: July 2023 Rainfall Impacts",
      "priority": "high",
      "retweets": null,
      "source": "Geoscience Today",
      "url": "https://eos.org/thelandslideblog/himachal-pradesh-1",
      "username": null
},
{
      "date": "2024-12-10T09:00:00",
      "disaster_type": "Flood",
      "Hastags": null,
      "likes": null,
      "location": "Delhi, India",
      "post_body": "A year after the 2023 Yamuna floods, many Delhi residents still struggle with the aftermath, and flood prevention measures remain insufficient.",
      "post_body_full": "The devastating floods of July 13, 2023, when the Yamuna river reached a record level of 208.66m, displaced over 23,000 people and caused widespread damage in Delhi. One year later, affected areas such as Mayur Vihar, ITO, and Civil Lines still show signs of the disaster. Residents express frustration over the lack of effective measures to prevent future flooding, with embankments and floodplains remaining vulnerable.",
      "post_id": "f1d2e3l4d5",
      "post_image_b64": null,
      "post_image_url": "https://images.hindustantimes.com/img/2024/07/12/550x309/A-year-since-the-floods--many-areas-still-bear-sca_1720807622151.jpg",
      "post_title": "Delhi Still Reeling from 2023 Yamuna Floods: A Year Later",
      "priority": "high",
      "retweets": null,
      "source": "Delhi Tribune",
      "url": "https://www.hindustantimes.com/cities/delhi-news/a-year-on-memories-of-2023-floods-linger-101720807666995.html",
      "username": null
},
{
      "date": "2024-12-10T11:30:00",
      "disaster_type": "Flood",
      "Hastags": null,
      "likes": null,
      "location": "Delhi, India",
      "post_body": "One year on, the scars of the 2023 Yamuna floods remain visible in Delhi. Affected residents demand stronger flood management measures.",
      "post_body_full": "The 2023 Yamuna floods brought widespread devastation to Delhi, with embankments breached and settlements submerged. Over 23,000 people were displaced as the river overflowed into areas like Mayur Vihar and Civil Lines. Despite the passage of time, many residents continue to live in damaged homes, and preventative measures remain inadequate. Experts warn of recurring risks unless robust flood management strategies are implemented.",
      "post_id": "f2g3h4d5l6",
      "post_image_b64": null,
      "post_image_url": "https://images.hindustantimes.com/img/2024/07/12/550x309/A-year-since-the-floods--many-areas-still-bear-sca_1720807622151.jpg",
      "post_title": "2023 Yamuna Floods: One Year Later, Delhi Awaits Relief",
      "priority": "high",
      "retweets": null,
      "source": "Capital News Network",
      "url": "https://www.hindustantimes.com/cities/delhi-news/a-year-on-memories-of-2023-floods-linger-101720807666995.html",
      "username": null
},
{
      "date": "2024-12-10T11:30:00",
      "disaster_type": "Flood",
      "Hastags": null,
      "likes": null,
      "location": "Delhi, India",
      "post_body": "One year on, the scars of the 2023 Yamuna floods remain visible in Delhi. Affected residents demand stronger flood management measures.",
      "post_body_full": "The 2023 Yamuna floods brought widespread devastation to Delhi, with embankments breached and settlements submerged. Over 23,000 people were displaced as the river overflowed into areas like Mayur Vihar and Civil Lines. Despite the passage of time, many residents continue to live in damaged homes, and preventative measures remain inadequate. Experts warn of recurring risks unless robust flood management strategies are implemented.",
      "post_id": "f2g3h4d5l6",
      "post_image_b64": null,
      "post_image_url": "https://images.hindustantimes.com/img/2024/07/12/550x309/A-year-since-the-floods--many-areas-still-bear-sca_1720807622151.jpg",
      "post_title": "2023 Yamuna Floods: One Year Later, Delhi Awaits Relief",
      "priority": "high",
      "retweets": null,
      "source": "Capital News Network",
      "url": "https://www.hindustantimes.com/cities/delhi-news/a-year-on-memories-of-2023-floods-linger-101720807666995.html",
      "username": null
}
]

export default data;